function checkForCSS(a){var b=/(<|&#60|u003C)\s*(\S+)\s*[^>]*\s*(>|&#62|u003E)(.*)(<|&#60|U003C)\/\s*\2\s*(>|&#62|u003E)/i,c=/((<|&#60|u003C).[^(><.)]+(>|&#62|u003E))/i,d=/(\s*\w+\s*)=\1/i;return/(<|&#60|u003C)\s*(\S+)\s*([^>]*)\s*(>|&#62|u003E)/i.test(a)||b.test(a)||c.test(a)||d.test(a)||!sqlInjection(a)?!1:!0}
function sqlInjection(a){var b=/((\%3D)|(&#61)|(u003D)|(=))[^\n]*((\%27)|(&#32)|(u0027)|(\')|(\-\-)|(\%3B)|(&#59)|(u003B)|(;))/i,c=/\w*((\%27)|(&#32)|(u0027)|(\'))(\s*)((\%6F)|(&#111)|(u006F)|o|(\%4F)|(&#79)|(u004F))((\%72)|(&#114)|(u0072)|r|(\%52)|(&#82)|(u0052))/i,d=/((\%27)|(&#32)|(u0027)|(\'))(\s*)(union|select|insert|update|delete|drop)/i,e=/exec(\s|\+)+(s|x)p\w+/i;return/(\%27)|(&#32)|(u0027)|(\')|(\-\-)|(\%23)|(&#35)|(u0023)|(#)/i.test(a)||b.test(a)||c.test(a)||d.test(a)||e.test(a)?!1:!0}
function securityCheck(a){a=a.value;return checkForCSS(a)&&sqlInjection(a)?!0:!1}function validationRequiredArr(a){var b,c=0,d="",e=!0;for(b=0;b<a.length;b++){var f=a[b][0];if("select"==f.type||"Select"==f.type){var h=f.selectedIndex;0<=h&&(value=f.options[h].value)}else value=f.value;if(0==trim(value).length||"select"==trim(value)||"Select"==trim(value))0==c&&c++,d=d+a[b][1]+"\n",e=!1}!1==e&&alert(d);return e}function trim(a){return a.replace(/^\s*/,"").replace(/\s*$/,"")}
function validationRequired(a){if("select-one"==a.type){var b=a.selectedIndex;0<=b&&(value=a.options[b].value)}else value=a.value;return 0==trim(value).length||"select"==trim(value)?!1:!0}function validateEmailv2(a){if(0>=a.length)return!0;a=a.match("^(.+)@(.+)$");return null==a||null!=a[1]&&null==a[1].match(/^\"?[\w-_\.]*\"?$/)?!1:null!=a[2]?null==a[2].match(/^[\w-\.]*\.[A-Za-z]{2,4}$/)&&null==a[2].match(/^\[\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\]$/)?!1:!0:!1}
function isNull(a){if(""==a.value||0==a.selectedIndex)return!0}function isEmail(a){var b=RegExp(/^([a-zA-Z]{1}[\w\-\.]*\@([\da-zA-Z\-]{1,}\.){1,}[\da-zA-Z\-]{2,4})$/);if(0==a.value.length)return!0;if(securityCheck(a))return!1==b.test(a.value)?(alert("Please Enter Valid EMail id ."),a.value="",!1):!0;alert("Malicious Code Found. Please Enter valid data.");a.value="";return!1}
function isAlphaNumeric(a){var b,c,d;b=a.value.length;c=a.value;if(securityCheck(a)){for(d=0;d<b;d++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-,.&!#() \n".indexOf(c.charAt(d)))return alert("Enter Alphabets or Numbers in the field"),a.value="",!1;return!0}alert("Malicious Code Found. Please Enter valid data.");a.value="";return!1}
function isNumeric_WhiteSpace(a){var b,c;b=a.value.length;c=a.value;if(securityCheck(a)){for(a=0;a<b;a++)if(-1==" 0123456789".indexOf(c.charAt(a)))return!1;return!0}alert("Malicious Code Found. Please Enter valid data.");return!1}
function isNumeric(a){var b,c,d;b=a.value.length;c=a.value;if(securityCheck(a)){for(d=0;d<b;d++)if(-1=="0123456789".indexOf(c.charAt(d)))return alert("Enter Numeric Data in this field"),a.value="",a.focus(),!1;return!0}alert("Malicious Code Found. Please Enter valid data.");a.value="";a.focus();return!1}
function isNumeric_DecimalNegative(a){var b,c,d,e,f;b=a.value.length;f=0;final_val="";c=a.value;if(securityCheck(a)){"-"==c.charAt(d)&&(c=c.substr(1,b),f=1);after_dec=dec_set=e=0;for(d=f;d<b;d++){if(1==dec_set&&(after_dec++,2<after_dec))return final_val=c.substr(0,d),a.value=final_val,alert("Only two digits are allowed after decimal"),!0;if("."==c.charAt(d)){if(0<e)return alert("Only one Decimal Point is allowed."),a.value="",!1;e++;dec_set=1}if(-1=="0123456789.".indexOf(c.charAt(d)))return alert("Enter Numeric Data in this field"),
a.value="",a.focus(),!1}return 0==dec_set&&11<b?(alert("Only 11 digits are allowed before decimal."),a.value="",a.focus(),!1):!0}alert("Malicious Code Found. Please Enter valid data.");return!1}function get_numeric(a){var b=a.value;len=a.value.length;for(i=0;i<len&&"0"==b.charAt(i);i++);"."==b.charAt(i)&&(i-=1);return b=b.substr(i,len)}
function isNumeric_Decimalround(a){var b,c,d,e;final_val="";after_dec=dec_set=e=0;if(securityCheck(a)){c=get_numeric(a);b=c.length;for(d=0;d<b;d++){if(1==dec_set&&(after_dec++,2<after_dec))return final_val=c.substr(0,d),a.value=final_val,alert("Only two digits are allowed after decimal."),!0;if("."==c.charAt(d)){if(0<e)return alert("Only one Decimal Point is allowed."),a.value="",!1;e++;dec_set=1}if(-1=="0123456789.".indexOf(c.charAt(d)))return alert("Enter Numeric Data in this field"),a.value="",
!1}if(0==dec_set&&13<b)return alert("Only 13 digits are allowed before decimal"),a.value="",!1;a.value=c;return!0}alert("Malicious Code Found. Please Enter valid data.");return!1}function isNumeric_Decimal(a){var b=RegExp(/(^\d{0,12}\.\d{1,2}$)|(^\d{0,15}$)/);if(securityCheck(a))return!1==b.test(a.value)?(alert("Please enter numeric data with two decimal places"),!1):!0;alert("Malicious Code Found. Please Enter valid data.");return!1}
function isAlpha(a){var b,c,d;b=a.value.length;c=a.value;if(securityCheck(a)){for(d=0;d<b;d++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-,.\n ".indexOf(c.charAt(d)))return alert("Enter only alphabets in this field"),a.value="",!1;return!0}alert("Malicious Code Found. Please Enter valid data.");return!1}
function isWebAdd(a){if(""!=a.value){a=a.value;var b=a.length,c=a.indexOf("."),d=c+1,e=a.substring(0,3),d=a.substring(d,b).indexOf(".");if(0==c||"."==a.charAt(b-1)||a.charAt(c)==a.charAt(c+1)||-1==d||"www"!=e)return alert("Enter Web Address starting with www"),!1}return!0}function isWhitespace(a){var b;if(isEmpty(a))return!0;for(b=0;b<a.length;b++){var c=a.charAt(b);if(-1==" \t\n\r".indexOf(c))return!1}return!0}function isEmpty(a){return null==a||0==a.length}var clearstatus=0;
function checkMaxLength(a,b,c){val=a.value;return val.length>b?(alert(c+" Length Should be less than "+b+" Characters"),a.focus(),!1):!0}function checkMendatory(a,b){val=a.value;return(val=1>val.length)?!1:!0}function checkMendatory(a){val=a.value;return(val=1>val.length)?!1:!0}function checkSpecialChar(a){value=a.value;for(var b=0;b<value.length;b++)if(-1!="%#*?&@#$%^\\'/|\"".indexOf(value.charAt(b)))return alert("Special characters are not allowed"),a.focus(),!1;return!0}
function fn_clear(a){for(var b=a.elements.length,c=0,c=0;c<b;c++)"text"==a.elements[c].type&&(a.elements[c].value=""),"select-one"==a.elements[c].type&&(a.elements[c].selectedIndex=0);clearstatus=1}var tempdate;function checkdate(a){return!1==chkdate(a)?(alert("The date is invalid.  Please try again."),a.value="",!1):!0}
function chkdate(a){var b,c,d,e,f,h=!1;f=["-"," ","/","."];var k,g=Array(12);g[0]="Jan";g[1]="Feb";g[2]="Mar";g[3]="Apr";g[4]="May";g[5]="Jun";g[6]="Jul";g[7]="Aug";g[8]="Sep";g[9]="Oct";g[10]="Nov";g[11]="Dec";b=a.value;if(5>=b.length||10<b.length)return!1;for(k=0;k<f.length;k++)if(-1!=b.indexOf(f[k])){c=b.split(f[k]);if(3!=c.length)return!1;d=c[0];e=c[1];c=c[2];h=!0}!1==h&&5<b.length&&(d=b.substr(0,2),e=b.substr(2,2),c=b.substr(4));if(3==c.length||4<c.length)return!1;1==c.length&&(c="200"+c);2==
c.length&&(c="20"+c);b=parseInt(d,10);if(isNaN(b))return!1;f=parseInt(e,10);10>f&&(f="0"+f);if(isNaN(f)){for(i=0;12>i;i++)e.toUpperCase()==g[i].toUpperCase()&&(f=i+1,e=g[i],i=12);if(isNaN(f))return!1}e=parseInt(c,10);if(isNaN(e)||12<f||1>f||(1==f||3==f||5==f||7==f||8==f||10==f||12==f)&&(31<b||1>b)||(4==f||6==f||9==f||11==f)&&(30<b||1>b))return!1;if(2==f){if(1>b)return!1;if(!0==LeapYear(e)){if(29<b)return!1}else if(28<b)return!1}tempdate=f+"/"+d+"/"+c;a.value=d+"/"+f+"/"+c;return!0}
function LeapYear(a){if(0==a%100){if(0==a%400)return!0}else if(0==a%4)return!0;return!1}function doSysdateCheck(a){var b=new Date;parseInt(b.getMonth()+1);parseInt(b.getYear());parseInt(b.getDate());return!1==chkdate(a)?(alert("Please enter valid date."),!1):Date.parse(tempdate)>Date.parse(b)?(alert("Date must occur before Today's  date."),!1):!0}function fnCheckPastDt(a){return!1==fnCompareDates(a.value,getTodayDateAmend())?(alert("Date cannot be a Future Date."),a.value="",a.focus(),!1):!0}
function isdoorno(a){var b,c,d,e;b=a.value.length;c=a.value;e="true";for(d=0;d<b;d++)-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-,.&!'#()/ ".indexOf(c.charAt(d))&&(e="false");"false"==e&&(alert("Enter Alphabets or Numbers\n or characters like -,.&!'#()/  in the field"),a.value="",a.focus());return!0}function leapYear(a){return 0==a%4?!0:!1}
function getDays(a,b){var c=Array(12);c[0]=31;c[1]=leapYear(b)?29:28;c[2]=31;c[3]=30;c[4]=31;c[5]=30;c[6]=31;c[7]=31;c[8]=30;c[9]=31;c[10]=30;c[11]=31;return c[a]}function fn_ValidatePhone(a){var b,c;b=a.length;for(c=0;c<b;c++)if(-1=="0123456789-".indexOf(a.charAt(c)))return alert("Enter Numeric Data in this field"),!1;return!0}
function securityCheckAll(){var a=!0,b=!0;textArr=document.getElementsByTagName("INPUT");for(var c=0;c<textArr.length;c++)b=securityCheck(textArr[c]),!1==b&&(a=!1);taArr=document.getElementsByTagName("TEXTAREA");for(c=0;c<taArr.length;c++)b=securityCheck(taArr[c]),!1==b&&(a=!1);if(!1==a)return alert("Please enter Valid  Values"),!1}
function isAlphabatic(a){var b,c;b=a.length;for(c=0;c<b;c++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz \n".indexOf(a.charAt(c)))return a.value="",!1;return!0}function isAlphabatic1(a){var b,c;b=a.value.length;for(c=0;c<b;c++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz ".indexOf(a.value.charAt(c)))return alert("Please enter alphabetic value, no special characters are allowed except space."),a.value="",!1;return!0}
function validurl(a){var b="",c=!0,d=RegExp(/(^((http\:\/\/)?[0-9A-Za-z\.]+)$)/);""!=a.value&&(matchPattern(a.value,d)||(b="Please enter valid website url",c=!1),""!=b&&alert(b));return c}
function fn_validatePAN(a){var b,c;b=a.value;c=b.length;"string"==typeof b&&(b=b.toUpperCase());a.value=b;for(var d=0;d<c;d++)if(-1!=".!@#$%^&*()+-".indexOf(b.charAt(d))){alert("This field should not contain special characters. Enter Again");a.value="";break}if(10!=c&&0!=c)return alert("Please enter a Valid PAN of length 10 characters"),a.value="",!1;10!=c||fn_isAlphaValue(b.substring(0,5))&&fn_isNumericValue(b.substring(5,9))&&fn_isAlphaValue(b.substring(9,10))||(alert("Please enter valid PAN (XXXXX9999X)"),
a.value="",a.focus())}function fn_isAlphaValue(a){var b;b=a.length;for(var c=0;c<b;c++)if(-1!="1234567890!@#$%^&*()+-".indexOf(a.charAt(c)))return!1;return!0}function fn_isNumericValue(a){var b;b=a.length;for(var c=0;c<b;c++)if(-1=="1234567890.".indexOf(a.charAt(c)))return!1;return!0}
function isAlphaNumericwithoutMessage(a){var b,c;b=a.value.length;c=a.value;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-,.&!#() \n".indexOf(c.charAt(a)))return!1;return!0}alert("Malicious Code Found. Please Enter valid data.");a.value="";return!1}
function fnCompareDates(a,b){var c,d;d=a.indexOf("/");var e=a.indexOf("/",3);c=a.substr(d+1,e-d-1)+"/"+a.substr(0,d)+"/"+a.substr(e+1,a.length);d=b.indexOf("/");e=b.indexOf("/",3);d=b.substr(d+1,e-d-1)+"/"+b.substr(0,d)+"/"+b.substr(e+1,b.length);return Date.parse(c)>Date.parse(d)?!1:!0}
function setToDate(a,b){var c=a.split("/"),d=c[1],c=c[2],e="",f="";if("Annually"==b||"ANNL"==b||"A"==b)f="31/03/"+("01"==d||"02"==d||"03"==d?c:1*c+1);else if("Quarterly"==b||"QRTR"==b||"Q"==b)if("01"==d||"02"==d||"03"==d)f="31/03/"+c;else if("04"==d||"05"==d||"06"==d)f="30/06/"+c;else if("07"==d||"08"==d||"09"==d)f="30/09/"+c;else{if("10"==d||"11"==d||"12"==d)f="31/12/"+c}else if("Monthly"==b||"MNTL"==b||"M"==b)"01"==d||"03"==d||"05"==d||"07"==d||"08"==d||"10"==d||"12"==d?e="31":"04"==d||"06"==d||
"09"==d||"11"==d?e="30":LeapYear(c)&&"02"==d?e="29":LeapYear(c)||"02"!=d||(e="28"),f=e+"/"+d+"/"+c;return TrimNew(f)}function TrimNew(a){a=LTrimNew(a);return RTrimNew(a)}function LTrimNew(a){for(;" "==a.charAt(0);)a=a.substring(1,a.length);return a}function RTrimNew(a){for(;" "==a.charAt(a.length-1);)a=a.substring(0,a.length-1);return a}
function compDate(a,b,c){var d=a.indexOf("/"),e=a.indexOf("/",3);a=a.substr(d+1,e-d-1)+"/"+a.substr(0,d)+"/"+a.substr(e+1,a.length);d=b.indexOf("/");e=b.indexOf("/",3);b=b.substr(d+1,e-d-1)+"/"+b.substr(0,d)+"/"+b.substr(e+1,b.length);return Date.parse(a)>Date.parse(b)?(alert(c),!1):!0}function checkAll(a,b){b.checked?selectAll(a,"1"):selectAll(a,"2")}
function selectAll(a,b){var c=document.getElementsByName(a);if(null!=c){var d=c.length;for(count=0;count<d;count++){var e=c[count];"checkbox"==e.type&&(e.checked="1"==b?"true":"")}}}
function valFutureDate(a){if(""!=a.value){var b=serverDate.split("/"),b=new Date(b[2],b[1]-1,b[0]),c=parseInt(b.getMonth()+1),d=parseInt(b.getYear()),b=parseInt(b.getDate())+"/"+c+"/"+d;if(!1==chkdate(a))return alert("Please enter date in dd/mm/yyyy format"),a.value="",a.focus(),!1;if(fnCompareDates(a.value,b))return!0;alert("Date should not be a future date.");a.value="";a.focus();return!1}}
function toDayDate(){var a=new Date,b=a.getMonth()+1,c=a.getDate(),a=a.getFullYear(),b=c+"/"+b+"/"+a,c=b.indexOf("/"),a=b.indexOf("/",3);return b.substr(c+1,a-c-1)+"/"+b.substr(0,c)+"/"+b.substr(a+1,b.length)}function checkBranchSpecialChar(a){value=a.value;for(var b=0;b<value.length;b++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-,.&()/ ".indexOf(value.charAt(b)))return alert("No special characters is allowed except -,.()&/ and space ."),a.focus(),!1;return!0}
function checkTextareaMaxLength(a,b){if(a.value.length>=b)return alert("You have exceeded the Maximum limit of "+b+"\nText above maxlimit will be truncated"),final_val=a.value.substr(0,b-1),a.value=final_val,a.focus(),!1}
function validateTIN(a){var b=a.value;if(null==b||""==b)return alert("PIN is required."),!1;if(securityCheck(a))if(11==b.length){if("A"!=b.substring(0,1).toString()&&"P"!=b.substring(0,1).toString()||isNaN(b.substring(1,10).toString()))return alert("Invalid PIN."),!1;a=b.substring(10).toString();for(b=flag=0;26>b;b++)a=="ABCDEFGHIJKLMNOPQRSTUVWXYZ".charAt(b)&&(flag=1);if(0==flag)return alert("Invalid PIN."),!1;flag=0}else return alert("Invalid PIN."),!1;else return alert("Malicious Code Found. Please Enter valid data."),
form1.value="",!1;return!0}function allowTodayAndFutureDate(a){if(!checkdate(a))return!1;var b=a.value,c=new Date,d=c.getMonth()+1,e=c.getDate(),c=c.getFullYear();return fnCompareDates(e+"/"+d+"/"+c,b)?!0:(alert("Date cannot be a past date"),a.value="",a.focus(),!1)}
function isEqual(a,b){var c,d;d=a.indexOf("/");var e=a.indexOf("/",3);c=a.substr(d+1,e-d-1)+"/"+a.substr(0,d)+"/"+a.substr(e+1,a.length);d=b.indexOf("/");e=b.indexOf("/",3);d=b.substr(d+1,e-d-1)+"/"+b.substr(0,d)+"/"+b.substr(e+1,b.length);return Date.parse(c)==Date.parse(d)?!0:!1};