var errorColor="#E26250",defaultColor="",errorListResult=Array(1E3),incError=0,AdFormJson=null,commonErrTabIndex=0;function hideAndShowTable(a){0<incError?document.getElementById(a).style.display="":document.getElementById(a).style.display="none"}function isErrorInList(a,b){return 0<incError?(tabview_switch(a,b),!0):!1}function getErrTabToggle(a,b){0==incError?hideTab(a,b):showTab(a,b)}function setCommonErrTabIndex(a){commonErrTabIndex=a}
function validateFormFields(){for(var a=0;a<arguments.length;a++)try{AdFormJson=arguments[a];for(var b=0;b<AdFormJson.field.length;b++){var c=AdFormJson.field[b].name;document.getElementById(c).value=trimStr(document.getElementById(c).value);var e=AdFormJson.field[b].rule[0];"radio"==document.getElementById(c).type.toLowerCase()?validateField(e,c):document.getElementById(c).disabled||"none"==document.getElementById(c).style.display||validateField(e,c)}}catch(f){return alert("Exception Occurred"+f.description),
!1}return 0<incError?!1:!0}
function validateFormFieldsOnIntrimSave(){for(var a=0;a<arguments.length;a++)try{AdFormJson=arguments[a];for(var b=0;b<AdFormJson.field.length;b++){var c=AdFormJson.field[b].name;document.getElementById(c).value=trimStr(document.getElementById(c).value);AdFormJson.field[b].rule[0].required="n";var e=AdFormJson.field[b].rule[0];"radio"==document.getElementById(c).type.toLowerCase()?validateField(e,c):document.getElementById(c).disabled||"none"==document.getElementById(c).style.display||validateField(e,
c)}}catch(f){return!1}return 0<incError?!1:!0}function validateAddRow(){for(var a=!0,b=0;b<arguments.length;b++){AdFormJson=arguments[b];for(var c=0;c<AdFormJson.field.length;c++){var e=AdFormJson.field[c].name;document.getElementById(e).value=trimStr(document.getElementById(e).value);var f=AdFormJson.field[c].rule[0];document.getElementById(e).disabled||"none"==document.getElementById(e).style.display||(a?a=validateField(f,e):validateField(f,e))}}return a}
function refreshErrorList(a){document.getElementById(a);for(var b=document.getElementById(a).getElementsByTagName("TBODY")[0],c=1;1E4>c;c++){var e=b.getElementsByTagName("TR")[0];if(null==e)break;else b.removeChild(e)}printErrorList(a)}function enableRequiredTab(a){try{for(var b=document.getElementById(a);"Page"!=b.className;)b=b.parentNode;var c=parseInt(b.id);tabview_switch("TabView",c)}catch(e){}document.getElementById(a).disabled||document.getElementById(a).focus()}
function errorObjClass(){this.isValidateOnIntrim=this.linkId=this.hdr=this.errMsg=this.id=null}
function generateServerSideError(a){errorListResult=eval("("+a+")");incError=errorListResult.length;a=Array(errorListResult.length);for(var b=0,c=0;c<incError;c++){var e=errorListResult[c].id;"chk"==e.substring(0,3)?(a[b++]=errorListResult[c],alert(errorListResult[c].errMsg)):(setErrorBGColor(e),document.getElementById(e).setAttribute("title",errorListResult[c].errMsg))}for(c=0;c<b;c++)rmvEleFrmArray(a[c]);refreshErrorList("errorTab")}
function resetErrorList(){for(var a=incError=0;a<arguments.length;a++)try{AdFormJson=arguments[a];for(var b=0;b<AdFormJson.field.length;b++){errorListResult.splice(b,1);var c=document.getElementById(AdFormJson.field[b].name);c.style.backgroundColor=defaultColor;c.removeAttribute("title")}}catch(e){}}
function resetErrorListOnIntrimSave(){var a=!1;try{for(var b=0;b<incError;b++)if(null!=errorListResult[b].isValidateOnIntrim&&"n"==errorListResult[b].isValidateOnIntrim){var c=document.getElementById(errorListResult[b].id);c.style.backgroundColor=defaultColor;c.removeAttribute("title");errorListResult.splice(b,1);incError-=1;b-=1;a=!0}a&&refreshErrorList("errorTab")}catch(e){alert(e.message)}}
function rmvEleFrmArray(a){for(var b=!1,c=0;c<incError;c++)errorListResult[c].id==a.id&&(errorListResult.splice(c,1),incError-=1,b=!0);b&&refreshErrorList("errorTab")}function rmvDisEleFrmArray(a){for(var b=!1,c=document.getElementById(a),e=0;e<incError;e++)if(errorListResult[e].id==a){errorListResult.splice(e,1);incError-=1;b=!0;setDefaultBGColor(a);c.removeAttribute("title");break}b&&refreshErrorList("errorTab")}
function printErrorList(a){a=document.getElementById(a).getElementsByTagName("TBODY")[0];for(var b=0;b<incError;b++){var c=document.createElement("TR"),e=document.createElement("TD"),f=document.createElement("TD");e.innerHTML="<center>"+(b+1)+"</center>";var d=document.createElement("a"),g=document.createTextNode(errorListResult[b].errMsg);d.setAttribute("href","javascript:enableRequiredTab('"+errorListResult[b].linkId+"')");d.appendChild(g);f.setAttribute("align","left");f.appendChild(d);c.appendChild(e);
c.appendChild(f);a.appendChild(c)}}function hgroupValidate(a){var b;try{for(var c=a.indexOf("_"),e=a.indexOf("_",c+1),f=a.substring(e+1,a.length),d=parseInt(f),f=0;1E4>f;f++){var g=a.substring(0,c+1)+(d+f)+a.substring(e,a.length);null!=document.getElementById(g)?checkMand(g)&&(b=!0):b=!1}}catch(h){b=!1}return b}
function vgroupValidate(a){var b;try{var c=a.indexOf("_"),e=a.indexOf("_",c+1),f=-1!=e?a.substring(c+1,e):a.substring(c+1,a.length),d=parseInt(f);b=!1;for(f=0;1E4>f;f++){var g=a.substring(0,c+1)+(d+f)+a.substring(e,a.length);if(null!=document.getElementById(g))b=checkMand(g)?!0:!1;else return b}}catch(h){}return b}function getVal(a){return document.getElementById(a).value}function trimStr(a){return null!=a&&""!=a?a.replace(/^\s+|\s+$/g,""):a}
function checkForCSS(a){var b=/(<|&#60|u003C)\s*(\S+)\s*[^>]*\s*(>|&#62|u003E)(.*)(<|&#60|U003C)\/\s*\2\s*(>|&#62|u003E)/i,c=/((<|&#60|u003C).[^(><.)]+(>|&#62|u003E))/i,e=/(\s*\w+\s*)=.*/i;return/(<|&#60|u003C)\s*(\S+)\s*([^>]*)\s*(>|&#62|u003E)/i.test(a)||b.test(a)||c.test(a)||e.test(a)||!sqlInjection(a)?!1:!0}
function sqlInjection(a){var b=/((\%3D)|(&#61)|(u003D)|(=))[^\n]*((\%27)|(&#32)|(u0027)|(\')|(\-\-)|(\%3B)|(&#59)|(u003B)|(;))/i,c=/\w*((\%27)|(&#32)|(u0027)|(\'))(\s*)((\%6F)|(&#111)|(u006F)|o|(\%4F)|(&#79)|(u004F))((\%72)|(&#114)|(u0072)|r|(\%52)|(&#82)|(u0052))/i,e=/((\%27)|(&#32)|(u0027)|(\'))(\s*)(union|select|insert|update|delete|drop)/i,f=/exec(\s|\+)+(s|x)p\w+/i;return/(\%27)|(&#32)|(u0027)|(\')|(\-\-)|(\%23)|(&#35)|(u0023)|(#)/i.test(a)||b.test(a)||c.test(a)||e.test(a)||f.test(a)?!1:!0}
function securityCheck(a){a=document.getElementById(a).value;return checkForCSS(a)&&sqlInjection(a)?!0:!1}
function checkMand(a){var b=null;try{b=document.getElementById(a).type.toLowerCase()}catch(c){alert("Javascript Exception Please Contact Administrator.")}if("radio"==b||"checkbox"==b){try{temp=a;var e,f=document.getElementById(temp),d=0;for(e=1;500>e;e++){f.disabled&&(d++,temp=a.substring(0,a.length-1)+e,f=document.getElementById(temp));if(f.checked)return!0;temp=a.substring(0,a.length-1)+e;f=document.getElementById(temp)}}catch(g){if(d==e)return!0}return!1}if("select-one"==b)return 0==document.getElementById(a).selectedIndex?
!1:!0;a=trimStr(document.getElementById(a).value);return null==a||""==a?!1:!0}function checkLength(a,b){return document.getElementById(a).value.length==b?!0:!1}function checkMinLength(a,b){return document.getElementById(a).value.length>=b?!0:!1}function checkMaxLength(a,b){return document.getElementById(a).value.length<=b?!0:!1}function checkMinMaxLength(a,b,c){return checkMinLength(a,b)&&checkMaxLength(a,c)?!0:!1}
function checkRegEx(a,b){var c=b.split("|"),e=!1;for(r=0;r<c.length&&!(e=RegExp(c[r]).test(document.getElementById(a).value));r++);return e}function isEmail(a){var b;a=document.getElementById(a).value;""!=a&&(b=-1!=a.search(/^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+(\.|-)?([A-Za-z0-9]+)*(\.)?([A-Za-z0-9]+)*\.[A-Za-z0-9]{2,4}$/)?!0:!1);return b}
function isValNumeric(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="0123456789.".indexOf(c.charAt(a)))return!1;return!0}return!1}function isUrl(a){return/^(?:https?:\/\/)?([a-z0-9\.-\/]{3,}\.[a-z]{3})/.test(document.getElementById(a).value.toLowerCase())?!0:!1}function isValOnlyBoolean(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="01".indexOf(c.charAt(a)))return!1;return!0}return!1}
function isValOnlyNumeric(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="0123456789".indexOf(c.charAt(a)))return!1;return!0}return!1}function isCurrency(a){var b=!1;return b=/^(-?[0-9][0-9,]*(.[0-9]{2})?)$/.test(document.getElementById(a).value)}function isAmount(a){var b=!1;return b=/^([0-9][0-9,]*(.[0-9]{2})?)$/.test(document.getElementById(a).value)}
function isAlphaWithDot(a){var b=!1;return b=/(^([A-Za-z]+([.]?[A-Za-z ]+)*([.]{0,1})))$/.test(document.getElementById(a).value)}function isDescription(a){var b=!1;return b=/(^([A-Za-z0-9 ]+([^A-Za-z0-9 ]{0,1}))+)$/.test(document.getElementById(a).value)}function isAlpha(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz ".indexOf(c.charAt(a)))return!1;return!0}return!1}
function isValAlphaNumeric(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%&:-_,/ .\n".indexOf(c.charAt(a))&&13!=c.charCodeAt(a))return!1;return!0}return!1}
function isValAlphaNumericBRG(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%&/".indexOf(c.charAt(a))&&13!=c.charCodeAt(a))return!1;return!0}return!1}
function isValOnlyAlphaNumeric(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%& ".indexOf(c.charAt(a)))return!1;return!0}return!1}function isValAlphaNumericWithoutSpace(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".indexOf(c.charAt(a)))return!1;return!0}return!1}
function isValAlphaNumericWthSpcChara(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%&:-,/ .\n".indexOf(c.charAt(a))&&13!=c.charCodeAt(a))return!1;return!0}return!1}
function isValAlphaNumericWthSpcCharForName(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%&(-)/,'.&".indexOf(c.charAt(a))&&13!=c.charCodeAt(a))return!1;return!0}return!1}
function isValAlphaNumericWthDot(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789/ .\n%&".indexOf(c.charAt(a))&&13!=c.charCodeAt(a))return!1;return!0}return!1}
function isBussNameWithSpecialChrs(a){var b,c;b=document.getElementById(a).value;a=b.length;for(c=0;c<a;c++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789/:-._,& ()'\n%&".indexOf(b.charAt(c))&&13!=b.charCodeAt(c))return!1;return!0}
function isAlphaNumericWithAllSpecChr(a){var b,c;b=document.getElementById(a).value;a=b.length;for(c=0;c<a;c++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789()[];:.,/ _@'\"-&%".indexOf(b.charAt(c))&&13!=b.charCodeAt(c))return!1;return!0}function isVehicleRegistrationNumber(a){var b=!1;return b=/^[a-zA-Z0-9-.\n]*$/.test(document.getElementById(a).value)}function isValSwiftCode(a){var b=!1;return b=/([A-Za-z]{8})/.test(document.getElementById(a).value)}
function isValAckNo(a){var b=!1;return b=/(KRA)[0-9]{12}/.test(document.getElementById(a).value)}function isValAlphaNumericWthSpcCharaWithSquareBracket(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_[]-/ \n".indexOf(c.charAt(a))&&13!=c.charCodeAt(a))return!1;return!0}return!1}
function validateFormFieldOnEvent(a,b){AdFormJson=b;var c=findRule(AdFormJson,a);return isValid=validateField(c,a)}
function isValAlphaNumericWthSpcCharaRemarks(a){var b,c;b=document.getElementById(a).value;a=b.length;for(c=0;c<a;c++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_()=':;-, .\\n".indexOf(b.charAt(c))&&13!=b.charCodeAt(c))return!1;return!0}
function validateField(a,b){document.getElementById(b).value=trimStr(document.getElementById(b).value);if(a){var c=document.getElementById(b),e=a.dispName,f=!1,d=null;if(null!=a.dependent){var g=a.dependent[0].ids,h=0,k=0,n=[],m=[],q=[],l=[],q=g.split(","),p=m=0,p=a.dependent[0].values,l=[];if(null!=p&&""!=p){for(;-1<h;)k=0==h?h:h+1,h=g.indexOf("&",k),-1<h?(n[m]=g.substring(k,h),l[m++]="and"):(h=g.indexOf("|",k),-1<h&&(n[m]=g.substring(k,h),l[m++]="or"));n[m]=g.substring(k,g.length);l[m++]="not";
m=p.split(",");p=m.length;for(g=0;g<p;g++)if(h=document.getElementById(n[g]).type.toLowerCase(),"radio"==h||"checkbox"==h)if(rtnChkRadioNo(n[g],m[g]))if(0==g)f=!0;else if("not"==l[g]){f=!0;break}else if("or"==l[g]){f=!0;break}else"and"==l[g]&&(f=!0);else if("or"==l[g])f=!1;else{f=!1;break}else if(document.getElementById(n[g]).value.toLowerCase()==m[g].toLowerCase())if("not"==l[g]){f=!0;break}else if("or"==l[g]){f=!0;break}else"and"==l[g]&&(f=!0);else if("or"==l[g])f=!1;else{f=!1;break}}if(null!=a.dependent[0].required)for(l=
a.dependent[0].required.split(","),r=0;r<q.length;r++)if("y"==l[r].toLowerCase())if(checkMand(q[r]))f=!0;else break;else if(checkMand(q[r]))break;else f=!0;f?a=a.dependent[0].rule[0]:(document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvDisEleFrmArray(b))}null!=a.required&&"n"==a.required.toLowerCase()&&(document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvDisEleFrmArray(b));if(null!=a.required&&"y"==a.required.toLowerCase())if(d=
new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.isValidateOnIntrim="n",checkMand(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),d.errMsg="Please select "+e,rmvEleFrmArray(d),d.errMsg="Please enter "+e,rmvEleFrmArray(d);else return setErrorBGColor(b),"text"==document.getElementById(b).type.toLowerCase()||"textarea"==document.getElementById(b).type.toLowerCase()?null!=a.ErrMsg?(c.setAttribute("title",a.ErrMsg),d.errMsg=a.ErrMsg):(c.setAttribute("title",
"Please enter "+e+""),d.errMsg="Please enter "+e):(null!=a.ErrMsg?(c.setAttribute("title",a.ErrMsg),d.errMsg=a.ErrMsg):(c.setAttribute("title","Please select "+e+""),d.errMsg="Please select "+e),d.errMsg="Please select "+e),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;if(null!=a.group)if("v"==a.group.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,vgroupValidate(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),
d.errMsg="Please enter "+e,rmvEleFrmArray(d);else return null!=a.ErrMsg?(c.setAttribute("title",a.ErrMsg),d.errMsg=a.ErrMsg):(c.setAttribute("title","Please enter "+e+""),d.errMsg="Please enter "+e),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("h"==a.group.toLowerCase())if(hgroupValidate(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),d.errMsg="Please enter "+e,rmvEleFrmArray(d);else return null!=a.ErrMsg?(c.setAttribute("title",
a.ErrMsg),d.errMsg=a.ErrMsg):(c.setAttribute("title","Please enter"+e+""),d.errMsg="Please enter "+e),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;if(null!=a.type&&null!=getVal(b)&&""!=getVal(b)){if("numeric"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter only numeric value",d.errMsg=null!=a.ErrMsg?a.ErrMsg:"Please enter valid "+e+".(Allowed character set: 0-9 and Dot)",isValNumeric(b)){document.getElementById(b).style.backgroundColor=
defaultColor;c.removeAttribute("title");rmvEleFrmArray(d);if(null!=a.minVal)if(f=parseInt(a.minVal),d=new errorObjClass,d.hdr=e,d.errMsg=null!=a.ErrMsg?a.ErrMsg:"Please enter value of "+e+" greater than "+f,chkMinVal(b,f))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please enter value of "+e+" greater than "+f+""),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),
!1;if(null!=a.maxVal)if(f=parseInt(a.maxVal),d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg=null!=a.ErrMsg?a.ErrMsg:"Please provide value of "+e+" less than "+f,chkMaxVal(b,f))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide value less than "+f+"."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1}else return null!=a.ErrMsg?
c.setAttribute("title",a.ErrMsg):c.setAttribute("title","Please enter valid "+e+".(Allowed character set: 0-9 and Dot)"),setErrorBGColor(b),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("alpha"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z and white space)",isAlpha(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);
else return setErrorBGColor(b),c.setAttribute("title","Please provide character value only."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("onlynumeric"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: 0-9)",isValOnlyNumeric(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),
c.setAttribute("title","Please Provide Only Numeric Value."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("currency"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: 0-9,. and comma)",isCurrency(b)){document.getElementById(b).style.backgroundColor=defaultColor;c.removeAttribute("title");rmvEleFrmArray(d);if(null!=a.minVal)if(f=parseInt(a.minVal),d=new errorObjClass,
d.hdr=e,d.errMsg=null!=a.ErrMsg?a.ErrMsg:"Please provide value of "+e+" greater than "+f,chkMinVal(b,f))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide value of "+e+" greater than "+f+""),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;if(null!=a.maxVal)if(f=parseInt(a.maxVal),d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg=
null!=a.ErrMsg?a.ErrMsg:"Please provide value of "+e+" less than 15 Digits",chkMaxVal(b,f))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide value less than 15 Digits."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1}else return setErrorBGColor(b),c.setAttribute("title","Please Provide Valid Currency Value"),rmvEleFrmArray(d),errorListResult[incError++]=
d,refreshErrorList("errorTab"),!1;else if("alphadot"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z and dot)",isAlphaWithDot(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please Provide Valid Alphabetic Value.(Allowed character set: A-Z and dot)"),rmvEleFrmArray(d),errorListResult[incError++]=
d,refreshErrorList("errorTab"),!1;else if("description"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please Provide Proper Value Only For "+e+".",isDescription(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please Provide Proper Value"),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("alphanumeric"==
a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z,0-9,/,:,-,,.,comma and white space)",isValAlphaNumeric(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide alphanumeric value only."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("alphanumericBRG"==
a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z,0-9,/)",isValAlphaNumericBRG(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide alphanumeric value only."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("alphanumericwithoutspace"==a.type.toLowerCase())if(d=
new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z and 0-9)",isValAlphaNumericWithoutSpace(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide alphanumeric withoutspace value only."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("onlyalphanumeric"==a.type.toLowerCase())if(d=
new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z,0-9 and white space)",isValOnlyAlphaNumeric(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide alphanumeric(number and alphabets) value."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("alphanumericspecialchara"==
a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z,0-9,/,:,-,.,comma and white space)",isValAlphaNumericWthSpcChara(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide alphanumeric value.Only Special characters like Space , - . / : are allowed."),rmvEleFrmArray(d),errorListResult[incError++]=
d,refreshErrorList("errorTab"),!1;else if("bussnamewithspecialchrs"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z,0-9,/,:,-,.,_,comma,&,(,),single quote and white space)",isBussNameWithSpecialChrs(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please enter alphanumeric value.Only Special characters like /,:,-,.,_,comma,&,(,),single quote and white space are allowed."),
rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;
else if('alphaNumericWthSpcCharaRemarks'== a.type)if(d=new errorObjClass(),	d.id=b,d.linkId=setErrorID(b),d.hdr=e,	d.errMsg='Please enter valid '+e+'.(Allowed character set: A-Z,0-9,\,:,-,.,=,_,;comma,single quote and white space)',isValAlphaNumericWthSpcCharaRemarks(b))	document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please enter alphanumeric value.Only Special characters (,),;,., _,=,-,comma,:,\' and space are allowed."),
rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;
else if("alphanumericwithallapecchrs"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z,0-9,/,;,:,-,.,&,(,),_,%,[,],single and double quotes,comma and white space)",isAlphaNumericWithAllSpecChr(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),
c.setAttribute("title","Please provide alphanumeric value.Only Special characters like /,:,-,.,&,(,),[,],-,%,;,single and double quotes,comma and white space are allowed."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("date"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+" in DD/MM/YYYY format.",isValidDate(b)){document.getElementById(b).style.backgroundColor=defaultColor;c.removeAttribute("title");
rmvEleFrmArray(d);if(null!=a.minVal)if(f=a.minVal,d.errMsg="Please provide "+e+" after or "+f,minDate(b,f))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide Date after or "+f+""),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;if(null!=a.maxVal)if(f=a.maxVal,d.errMsg="Please provide "+e+" before or "+f,maxDate(b,f))document.getElementById(b).style.backgroundColor=
defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide Date before or "+f+"."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1}else return setErrorBGColor(b),c.setAttribute("title","Please provide valid date in DD/MM/YYYY format."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("email"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),
d.hdr=e,d.errMsg="Please enter valid "+e,isEmail(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please enter valid "+e),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("url"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid url.",isUrl(b))document.getElementById(b).style.backgroundColor=
defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please enter valid url."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("amount"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: 0-9,. and comma)",isAmount(b)){document.getElementById(b).style.backgroundColor=defaultColor;c.removeAttribute("title");rmvEleFrmArray(d);
if(null!=a.minVal)if(f=parseInt(a.minVal),d=new errorObjClass,d.hdr=e,d.errMsg=null!=a.ErrMsg?a.ErrMsg:"Please provide value of "+e+" greater than "+f,chkMinVal(b,f))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide value of "+e+" greater than "+f+""),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;if(null!=a.maxVal)if(f=parseInt(a.maxVal),
d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg=null!=a.ErrMsg?a.ErrMsg:"Please provide value of "+e+" less than 15 Digits",chkMaxVal(b,f))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide value less than 15 Digits."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1}else return setErrorBGColor(b),c.setAttribute("title","Please Provide Valid Currency Value"),
rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("swiftcode"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Length must be 8. Allowed character set: A-Z)",isValSwiftCode(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide alphanumeric value"),rmvEleFrmArray(d),errorListResult[incError++]=
d,refreshErrorList("errorTab"),!1;else if("vehicleregistrationnumber"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z,0-9,-.)",isVehicleRegistrationNumber(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide alphanumeric value.Only Special character - and . is  allowed."),rmvEleFrmArray(d),
errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("ackNo"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".",isValAckNo(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide alphanumeric value"),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("alphanumericwthspccharawithsquarebracket"==
a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z,0-9,/,_,-[]comma and white space)",isValAlphaNumericWthSpcCharaWithSquareBracket(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide alphanumeric value.Only Special characters like Space , - . / : []are allowed."),rmvEleFrmArray(d),
errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("alphanumericwthdot"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z,0-9,/., and white space)",isValAlphaNumericWthDot(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide alphanumeric value.Only Special characters like Space . / are allowed."),
rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("alphanumericSpcCharForName"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z,0-9,(,-,),/,\u2018,.,&, comma and white space)",isValAlphaNumericWthSpcCharForName(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title",
"Please provide alphanumeric value. Only Special characters like Space (-)/,\u2018.& are allowed."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("isValAlphaNumericWthBrackets"==a.type)if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z,0-9,(,-,),/,\u2018,.,&,', comma and white space)",isValAlphaNumericWthBrackets(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title",
"Please provide alphanumeric value. Only Special characters like Space (-)/,\u2018.& are allowed."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;if(null!=a.regEx){f=a.regEx;d=new errorObjClass;d.id=b;d.linkId=setErrorID(b);d.hdr=e;null!=a.ErrMsg?(c.setAttribute("title",a.ErrMsg),d.errMsg=a.ErrMsg):(c.setAttribute("title","Please provide proper value of "+e+"."),d.errMsg="Please provide proper value of "+e+".");if(!checkRegEx(b,f)&&(null==a.required||"n"!=a.required||
checkMand(b)))return setErrorBGColor(b),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;document.getElementById(b).style.backgroundColor=defaultColor;c.removeAttribute("title");rmvEleFrmArray(d)}if(null!=a.maxLength)if(f=parseInt(a.maxLength),d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Maximum length should be "+f+")",checkMaxLength(b,f))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),
rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please enter valid "+e+".(Maximum length should be "+f+")"),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;if(null!=a.minLength)if(f=parseInt(a.minLength),d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Minimum length should be "+f+")",checkMinLength(b,f))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),rmvEleFrmArray(d);
else return setErrorBGColor(b),c.setAttribute("title","Please enter valid "+e+".(Minimum length should be "+f+")"),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1;else if("alphanumericspecialcharatss"==a.type.toLowerCase())if(d=new errorObjClass,d.id=b,d.linkId=setErrorID(b),d.hdr=e,d.errMsg="Please enter valid "+e+".(Allowed character set: A-Z,a-z,0-9,%,&,,,-,.])",isValAlphaNumericDescTSS(b))document.getElementById(b).style.backgroundColor=defaultColor,c.removeAttribute("title"),
rmvEleFrmArray(d);else return setErrorBGColor(b),c.setAttribute("title","Please provide alphanumeric value.Only Special characters like % & , - . ] are allowed."),rmvEleFrmArray(d),errorListResult[incError++]=d,refreshErrorList("errorTab"),!1}}return!0}function rtnChkRadioNo(a,b){var c=a;try{for(var e=document.getElementById(c),f=2;500>f;f++){if(e.checked)return e.value.toLowerCase()==b.toLowerCase()?!0:!1;c=a.substring(0,a.length-1)+f;e=document.getElementById(c)}}catch(d){}return!1}
function findRule(a,b){var c,e=a.field.length;for(c=0;c<e;c++)if(a.field[c].name.toLowerCase()==b.toLowerCase())return a.field[c].rule[0];return!1}function chkMinVal(a,b){return parseInt(document.getElementById(a).value)>=b?!0:!1}function chkMaxVal(a,b){return parseInt(document.getElementById(a).value)<=b?!0:!1}
function disableElements(a){try{a.disabled||rmvDisEleFrmArray(a.id),a.disabled=a.disabled?!1:!0}catch(b){}if(a.childNodes&&0<a.childNodes.length)for(var c=0;c<a.childNodes.length;c++)disableElements(a.childNodes[c])}
function minDate(a,b){var c=document.getElementById(a).value,e=parseInt(c.substring(0,2),10),f=parseInt(c.substring(3,5),10),c=parseInt(c.substring(6,10),10),d=parseInt(b.substring(0,2),10),g=parseInt(b.substring(3,5),10),h=parseInt(b.substring(6,10),10);return new Date(c,f,e)>=new Date(h,g,d)?!0:!1}
function maxDate(a,b){var c=document.getElementById(a).value,e=parseInt(c.substring(0,2),10),f=parseInt(c.substring(3,5),10),c=parseInt(c.substring(6,10),10),d=parseInt(b.substring(0,2),10),g=parseInt(b.substring(3,5),10),h=parseInt(b.substring(6,10),10);return new Date(c,f,e)<=new Date(h,g,d)?!0:!1}
function isEqual(a,b){var c,e;e=a.indexOf("/");var f=a.indexOf("/",3);c=a.substr(e+1,f-e-1)+"/"+a.substr(0,e)+"/"+a.substr(f+1,a.length);e=b.indexOf("/");f=b.indexOf("/",3);e=b.substr(e+1,f-e-1)+"/"+b.substr(0,e)+"/"+b.substr(f+1,b.length);return Date.parse(c)==Date.parse(e)?!0:!1}function isSlashDtFrmt(a){if(null!=a.value&&""!=a.value)return-1==a.value.indexOf("/")?(alert("please enter date in dd/mm/yyyy format"),a.value="",!1):!0}
function isValidDate(a){var b,c,e,f,d;d=!1;a=getVal(a);if(""==trimStr(a)||null==trimStr(a))return!0;var g=["-"," ","/","."],h,k=Array(12);k[0]="Jan";k[1]="Feb";k[2]="Mar";k[3]="Apr";k[4]="May";k[5]="Jun";k[6]="Jul";k[7]="Aug";k[8]="Sep";k[9]="Oct";k[10]="Nov";k[11]="Dec";b=trimStr(a);if(5>=b.length||10<b.length)return!1;for(h=0;h<g.length;h++)if(-1!=b.indexOf(g[h])){c=b.split(g[h]);if(3!=c.length)return!1;e=c[0];f=c[1];c=c[2];d=!0}if(!1==d||3==c.length||4<c.length)return!1;1==c.length&&(c="200"+c);
2==c.length&&(c="20"+c);if(isNaN(e))return!1;b=parseInt(e,10);if(isNaN(b)||isNaN(f))return!1;d=parseInt(f,10);10>d&&(d="0"+d);if(isNaN(d))for(i=0;12>i;i++)f.toUpperCase()==k[i].toUpperCase()&&(d=i+1,f=k[i],i=12);if(isNaN(c))return!1;f=parseInt(c,10);if(12<d||1>d||(1==d||3==d||5==d||7==d||8==d||10==d||12==d)&&(31<b||1>b)||(4==d||6==d||9==d||11==d)&&(30<b||1>b))return!1;if(2==d){if(1>b)return!1;if(!0==LeapYear(f)){if(29<b)return!1}else if(28<b)return!1}tempdate=d+"/"+e+"/"+c;a.value=e+"/"+d+"/"+c;return!0}
function LeapYear(a){if(0==a%100){if(0==a%400)return!0}else if(0==a%4)return!0;return!1}function setErrorBGColor(a){try{var b=document.getElementById(a);if(b.disabled){a=a.substring(0,a.length-1);for(var c=2;5E3>c;c++)if(b=document.getElementById(a+c),!b.disabled){b.style.backgroundColor=errorColor;break}}else b.style.backgroundColor=errorColor}catch(e){}}
function setDefaultBGColor(a){try{var b=document.getElementById(a);if(b.disabled){a=a.substring(0,a.length-1);for(var c=2;5E3>c;c++)if(b=document.getElementById(a+c),!b.disabled){b.style.backgroundColor=defaultColor;break}}else b.style.backgroundColor=defaultColor}catch(e){}}
function setErrorID(a){var b;try{var c=document.getElementById(a);if(c.disabled){var e=a.substring(0,a.length-1);for(a=2;5E3>a;a++){var f=e+a,c=document.getElementById(f);if(!c.disabled){b=f;break}}}else b=a}catch(d){}return b}function getMinDate(a,b){var c=parseInt(a.substring(0,2),10),e=parseInt(a.substring(3,5),10),f=parseInt(a.substring(6,10),10),d=parseInt(b.substring(0,2),10),g=parseInt(b.substring(3,5),10),h=parseInt(b.substring(6,10),10);return new Date(f,e,c)>=new Date(h,g,d)?b:a}
function setCurrentPageDetails(a){if(""==document.getElementById("currentPage").value||""==document.getElementById("lastPage").value)return!1;if("Next"==a){if(document.getElementById("currentPage").value<document.getElementById("lastPage").value)return document.getElementById("currentPage").value++,!0;alert("You are currently on last page");return!1}if("Prev"==a){if(1<document.getElementById("currentPage").value)return document.getElementById("currentPage").value--,!0;alert("You are currently on first page");
return!1}if("First"==a){if(1<document.getElementById("currentPage").value)return document.getElementById("currentPage").value=1,!0;alert("You are currently on first page");return!1}if("Last"==a)if(document.getElementById("currentPage").value<document.getElementById("lastPage").value)document.getElementById("currentPage").value=document.getElementById("lastPage").value;else return alert("You are currently on last page"),!1;return!0}
function validatePageRange(a){return parseInt(document.getElementById("txtGoToPage").value)>a||1>document.getElementById("txtGoToPage").value?(alert("please enter the page number in proper range"),!1):!0}
function disabledElements(a,b){try{if("textarea"==a.type||"text"==a.type||"select-one"==a.type||"submit"==a.type||"checkbox"==a.type||"radio"==a.type||"button"==a.type||null!=a.href)a.disabled=b}catch(c){}if(a.childNodes&&0<a.childNodes.length)for(var e=0;e<a.childNodes.length;e++)disabledElements(a.childNodes[e],b)}
function clearAll(){for(var a=document.getElementsByTagName("input"),b=0;b<a.length;b++)"text"==a[b].type?a[b].value="":"checkbox"==a[b].type?a[b].checked=!1:"radio"==a[b].type?a[b].checked=!1:-1!=a[b].id.indexOf("_hidden")&&(a[b].value="");b=document.getElementsByTagName("textarea");for(a=0;a<b.length;a++)b[a].value="";for(var b=document.getElementsByTagName("select"),c=0;c<b.length;c++)b[a].selectedIndex=0}
function ageValidation(a,b){dob=document.getElementById(a).value;var c=dob.split("-"),e=c[0],f=c[1],c=c[2];currDate=new Date;currYear=currDate.getFullYear();currMon=currDate.getMonth();currDate=currDate.getDate();age=currYear-c;f<currMon+1?age-=1:f==currMon+1&&e<currDate&&(age-=1);age<b&&(alert("Age should not be less than "+b+" years"),document.getElementById(a).value="")}
function ageValidationForSlashFormat(a,b){dob=document.getElementById(a).value;var c=dob.split("/"),e=c[0],f=c[1],c=c[2];currDate=new Date;currYear=currDate.getFullYear();currMon=currDate.getMonth();currDate=currDate.getDate();age=currYear-c;currMon+1<f?age-=1:f==currMon+1&&currDate<e&&(age-=1);return age<b?(alert("Age should not be less than "+b+" years"),document.getElementById(a).value="",!1):!0}
function chkAge(a,b){dob=document.getElementById(a).value;var c=dob.split("/"),e=c[0],f=c[1],c=c[2];currDate=new Date;currYear=currDate.getFullYear();currMon=currDate.getMonth();currDate=currDate.getDate();age=currYear-c;currMon+1<f?age-=1:f==currMon+1&&currDate<e&&(age-=1);return age>b?(alert("Age should not be greater than "+b+" years"),document.getElementById(a).value="",!1):!0}
function allowFutureDateOnly(a){if(""!=document.getElementById(a).value){var b=new Date,c=parseInt(b.getMonth()+1);10>c&&(c="0"+c);var e=parseInt(b.getFullYear()),b=parseInt(b.getDate());10>b&&(b="0"+b);if(futureDateCheck(a,b+"-"+c+"-"+e))return!0;alert("Date should not be past or today's date");document.getElementById(a).value=""}return!1}
function allowTodayAndPastDate(a){if(""!=document.getElementById(a).value){var b=new Date,c=parseInt(b.getMonth()+1);10>c&&(c="0"+c);var e=parseInt(b.getFullYear()),b=parseInt(b.getDate());10>b&&(b="0"+b);if(maxDate(a,b+"-"+c+"-"+e))return!0;alert("Date should not be future date");document.getElementById(a).value=""}return!1}
function futureDateCheck(a,b){var c=document.getElementById(a).value,e=parseInt(c.substring(0,2),10),f=parseInt(c.substring(3,5),10),c=parseInt(c.substring(6,10),10),d=parseInt(b.substring(0,2),10),g=parseInt(b.substring(3,5),10),h=parseInt(b.substring(6,10),10);return new Date(c,f,e)>new Date(h,g,d)?!0:!1}var frmSubmitFlag=0,iSec=null;
function crtDynamicDivForSubmit(){dv=document.createElement("div");dv.setAttribute("id","blankImage");dv.className="forBlankImageToBlur";dv.innerHTML="&nbsp;";dv1=document.createElement("div");dv1.className="forAjaxImage";dv1.innerHTML="&nbsp";dv.appendChild(dv1);document.forms[0].appendChild(dv)}function submitform(a){0==frmSubmitFlag&&(crtDynamicDivForSubmit(),document.getElementById("blankImage").style.display="block",frmSubmitFlag=1)}
function allowTodayAndFutureDateOnly(a){if(""!=document.getElementById(a).value){var b=new Date,c=parseInt(b.getMonth()+1);10>c&&(c="0"+c);var e=parseInt(b.getFullYear()),b=parseInt(b.getDate());10>b&&(b="0"+b);if(todayAndFutureDateCheck(a,b+"-"+c+"-"+e))return!0;alert("Date should not be past date");document.getElementById(a).value=""}return!1}
function todayAndFutureDateCheck(a,b){var c=document.getElementById(a).value,e=parseInt(c.substring(0,2),10),f=parseInt(c.substring(3,5),10),c=parseInt(c.substring(6,10),10),d=parseInt(b.substring(0,2),10),g=parseInt(b.substring(3,5),10),h=parseInt(b.substring(6,10),10);return new Date(c,f,e)>=new Date(h,g,d)?!0:!1}
function addTitle(a){if(null!=a&&""!=a&&(a=document.getElementById(a),null!=a&&null!=a.options&&0<a.options.length))for(var b=0;b<a.options.length;b++)a.options[b].title=a.options[b].text}
function loadEditor(a,b,c,e){var f=new WYSIWYG.Settings;f.ImagesDir=a+f.ImagesDir;f.removeToolbarElement("undo");f.removeToolbarElement("redo");f.removeToolbarElement("createlink");f.removeToolbarElement("print");f.removeToolbarElement("help");f.removeToolbarElement("maximize");f.removeToolbarElement("maximize");f.removeToolbarElement("forecolor");f.removeToolbarElement("backcolor");f.removeToolbarElement("inserttable");f.removeToolbarElement("insertimage");f.removeToolbarElement("preview");f.removeToolbarElement("removeformat");
c?f.URL=e:f.removeToolbarElement("save");f.removeToolbarElement("seperator");f.Width="100%";WYSIWYG.attach(b,f)}var sUserInfo="",iSessionTimeout,iSessionTime="",sessionflag=!0,sessionExpiredFlag=!1;function initSessionTimeOutVar(a,b){sUserInfo=a;iSessionTimeout=60*parseInt(b);ShowSessionTimeout()}
function ShowSessionTimeout(){var a=0;""==iSessionTime&&(iSessionTime=parseInt(iSessionTimeout/60));0<iSessionTimeout?(iMinutes=parseInt(iSessionTimeout/60),a=iSessionTimeout%60,window.status=""!=sUserInfo?sUserInfo+". Your session will expire within "+iMinutes+" minute(s) and "+a+" second(s).":"Your session will expire within "+iMinutes+" minute(s) and "+a+" second(s).",2==iMinutes&&0==a&&(parseInt((new Date).getTime()/1E3),alert("Dear User, you have not clicked on any link or button for the last "+
(iSessionTime-iMinutes)+" minutes. Please click on any link or button within next "+iMinutes+" minutes.")),iSessionTimeout-=1,window.setTimeout("ShowSessionTimeout()",1E3)):(window.status=sUserInfo+" Your session expired, Please log on afresh.",sessionExpiredFlag=!0,document.forms.headerForm.submit())}
function pastDateCheck(a,b){var c=document.getElementById(a).value,e=parseInt(c.substring(0,2),10),f=parseInt(c.substring(3,5),10),c=parseInt(c.substring(6,10),10),d=parseInt(b.substring(0,2),10),g=parseInt(b.substring(3,5),10),h=parseInt(b.substring(6,10),10);return new Date(c,f,e)<new Date(h,g,d)?!0:!1}
function validateWebsite(a){null==a.value||""==a.value||/^(((http|https){1}(:[/][/]){1})((www.){1})|((www.){1}))[-a-zA-Z0-9@:%_\+.~#?&//=]+$/.test(a.value)||(alert("Please enter valid website URL."),a.value="")}
function validateFormFieldsOnIntrimSave(){for(var a=0;a<arguments.length;a++)try{AdFormJson=arguments[a];for(var b=0;b<AdFormJson.field.length;b++){var c=AdFormJson.field[b].name;AdFormJson.field[b].rule[0].required="n";var e=AdFormJson.field[b].rule[0];"radio"==document.getElementById(c).type.toLowerCase()?validateField(e,c):document.getElementById(c).disabled||"none"==document.getElementById(c).style.display||validateField(e,c)}}catch(f){return!1}return 0<incError?!1:!0}
function isValNumericWithComma(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="0123456789.,".indexOf(c.charAt(a)))return!1;return!0}return!1}function isValAlphaNumericDescTSS(a){var b,c;c=document.getElementById(a).value;b=c.length;if(securityCheck(a)){for(a=0;a<b;a++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%&,-.]".indexOf(c.charAt(a))&&13!=c.charCodeAt(a))return!1;return!0}return!1};
function isValAlphaNumericWthBrackets(a){var b,c;c=document.getElementById(a).value;b=c.length;for(a=0;a<b;a++)if(-1=="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789:-_,/ .\n%&(')".indexOf(c.charAt(a))&&13!=c.charCodeAt(a))return!1;return!0};